# For all possible configuration options see:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "daily"
    allow:
      # Allow both direct and indirect updates for all crates.
      - dependency-type: "all"
    ignore:
      # Updating some of our dependencies would break the MSRV build, so they
      # are ignored.
      - dependency-name: "csv"
      - dependency-name: "once_cell"
      - dependency-name: "regex"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
