alpine:
  image: alpine:latest
  stage: build
  before_script:
    - apk update update
    - apk add bash php-cli php-json php-pdo_sqlite
  script:
    - php --version
    - ./ci/phplint.sh
    - php ./src/generate.php ./data/corona.db /tmp/output_directory

centos:
  image: centos:8
  stage: build
  before_script:
    - yum install -y bash php-cli php-json php-pdo
  script:
    - php --version
    - ./ci/phplint.sh
    - php ./src/generate.php ./data/corona.db /tmp/output_directory

debian:
  image: debian:10-slim
  stage: build
  before_script:
    - apt-get update
    - export DEBIAN_FRONTEND=noninteractive
    - apt-get install -y bash php-cli php-json php-sqlite3
  script:
    - php --version
    - ./ci/phplint.sh
    - php ./src/generate.php ./data/corona.db /tmp/output_directory
