alpine:
  image: alpine:latest
  stage: build
  retry: 2
  before_script:
    - apk update
    - apk add bash cargo rust sqlite-dev openssl-dev
  script:
    - rustc --version
    - cargo --version
    - cargo run -- version
    - cargo test || cargo test || cargo test

bionic_failcheck:
  image: ubuntu:bionic
  stage: build
  before_script:
    - apt-get update
    - export DEBIAN_FRONTEND=noninteractive
    - apt-get install -y bash cargo rustc libsqlite3-dev libssl-dev pkg-config
  script:
    - rustc --version
    - cargo --version
    - ./ci/failcheck_sqlite.sh

build_image_rocky:
  image: docker:20
  stage: build
  services:
    - docker:20-dind
  script:
    - cd ci/
    - docker build -t $CI_REGISTRY/striezel/corona/ci-rocky:8 . -f Dockerfile_rocky
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker push $CI_REGISTRY/striezel/corona/ci-rocky:8
    - docker logout $CI_REGISTRY
  # Only build new image when the Dockerfile or the GitLab CI configuration
  # changes.
  only:
    changes:
      - ci/Dockerfile_rocky
      - .gitlab-ci.yml

rocky:
  image: registry.gitlab.com/striezel/corona/ci-rocky:8
  stage: build
  retry: 2
  before_script:
    - yum update -y
  script:
    - rustc --version
    - cargo --version
    - cargo run -- version
    - cargo test || cargo test || cargo test

build_image_debian:
  image: docker:20
  stage: build
  services:
    - docker:20-dind
  script:
    - cd ci/
    - docker build -t $CI_REGISTRY/striezel/corona/ci-debian:11 . -f Dockerfile_debian
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker push $CI_REGISTRY/striezel/corona/ci-debian:11
    - docker logout $CI_REGISTRY
  # Only build new image when the Dockerfile or the GitLab CI configuration
  # changes.
  only:
    changes:
      - ci/Dockerfile_debian
      - .gitlab-ci.yml

debian:
  image: registry.gitlab.com/striezel/corona/ci-debian:11
  stage: build
  retry: 2
  before_script:
    - apt-get update
    - export DEBIAN_FRONTEND=noninteractive
    - apt-get upgrade -y
  script:
    - rustc --version
    - cargo --version
    - cargo run -- version
    - cargo test || cargo test || cargo test

clippy:
  image: alpine:latest
  stage: build
  before_script:
    - apk update
    - apk add bash curl wget sqlite-dev gcc g++ openssl-dev
    - wget -O /tmp/ru.sh https://sh.rustup.rs
    - chmod u+x /tmp/ru.sh
    - /tmp/ru.sh -y --profile minimal --component clippy
    - source $HOME/.cargo/env
    - export PATH="$HOME/.cargo/bin:$PATH"
  script:
    - rustc --version
    - cargo --version
    - cargo clippy -- -D warnings
