pages:
  stage: deploy
  script:
    - mkdir public
    - cp ./*.html public/
    - mkdir public/assets
    - cp assets/* public/assets
    # copy older stuff, too
    - cp -R ecdc public
    - cp -R jhu public
    - cp -R owid public
    - cp -R who public
  artifacts:
    paths:
      - public
  only:
    - gh-pages
