alpine:
  image: alpine:latest
  stage: build
  before_script:
    - apk update
    - apk add bash cargo rust
  script:
    - rustc --version
    - cargo --version
    - cd rust && cargo test

centos:
  image: centos:8
  stage: build
  before_script:
    - yum install -y bash cargo rust
  script:
    - rustc --version
    - cargo --version
    - cd rust && cargo test

debian:
  image: debian:10-slim
  stage: build
  before_script:
    - apt-get update
    - export DEBIAN_FRONTEND=noninteractive
    - apt-get install -y bash cargo rustc
  script:
    - rustc --version
    - cargo --version
    - cd rust && cargo test
