alpine:
  image: alpine:latest
  stage: build
  retry: 2
  before_script:
    - apk update
    - apk add bash cargo rust sqlite-dev openssl-dev
  script:
    - rustc --version
    - cargo --version
    - cargo run -- version
    - cargo test

bionic_failcheck:
  image: ubuntu:bionic
  stage: build
  before_script:
    - apt-get update
    - export DEBIAN_FRONTEND=noninteractive
    - apt-get install -y bash cargo rustc libsqlite3-dev libssl-dev pkg-config
  script:
    - rustc --version
    - cargo --version
    - ./ci/failcheck_sqlite.sh

rocky:
  image: rockylinux:8
  stage: build
  retry: 2
  before_script:
    - yum install -y bash cargo rust sqlite-devel openssl-devel
  script:
    - rustc --version
    - cargo --version
    - cargo run -- version
    - cargo test

debian:
  image: debian:11-slim
  stage: build
  retry: 2
  before_script:
    - apt-get update
    - export DEBIAN_FRONTEND=noninteractive
    - apt-get install -y bash cargo rustc libsqlite3-dev libssl-dev pkg-config
  script:
    - rustc --version
    - cargo --version
    - cargo run -- version
    - cargo test

clippy:
  image: alpine:latest
  stage: build
  before_script:
    - apk update
    - apk add bash curl wget sqlite-dev gcc g++ openssl-dev
    - wget -O /tmp/ru.sh https://sh.rustup.rs
    - chmod u+x /tmp/ru.sh
    - /tmp/ru.sh -y --profile minimal --component clippy
    - source $HOME/.cargo/env
    - export PATH="$HOME/.cargo/bin:$PATH"
  script:
    - rustc --version
    - cargo --version
    - cargo clippy -- -D warnings
