brace_style = "AlwaysNextLine"
control_brace_style = "AlwaysNextLine"
empty_item_single_line = false
newline_style = "Unix"
space_after_colon = true
tab_spaces = 2
trailing_comma = "Never"
type_punctuation_density = "Wide"
unstable_features = true
use_field_init_shorthand = true
