os: Visual Studio 2019

environment:
  matrix:
# Build channels stable, beta and nightly for 64 bit on MSVC.
    - channel: stable
      target: x86_64-pc-windows-msvc
    - channel: beta
      target: x86_64-pc-windows-msvc
    - channel: nightly
      target: x86_64-pc-windows-msvc
# Build stable channel for 32 bit on MSVC.
    - channel: stable
      target: i686-pc-windows-msvc
# Build channels stable, beta and nightly for 64 bit on GNU.
    - channel: stable
      target: x86_64-pc-windows-gnu
    - channel: beta
      target: x86_64-pc-windows-gnu
    - channel: nightly
      target: x86_64-pc-windows-gnu
# Build stable channel for 32 bit.
    - channel: stable
      target: i686-pc-windows-gnu

matrix:
  allow_failures:
    - channel: nightly

install:
  - appveyor DownloadFile https://win.rustup.rs/ -FileName rustup-init.exe
  - rustup-init -yv --default-toolchain %channel% --default-host %target%
  - set PATH=%PATH%;%USERPROFILE%\.cargo\bin
  - rustc --version --verbose
  - cargo --version

# 'cargo test' takes care of building, so disable Appveyor's build stage.
build: false
test_script:
  - cargo test --verbose %cargoflags%
