[package]
name = "corona"
version = "0.1.0"
authors = ["Dirk Stolle <striezel-dev@web.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.4.2"
rusqlite = "0.24.2"
