name: MacOS

on: push
jobs:
  build-macos:
    runs-on: ${{ matrix.os }}-14
    strategy:
      matrix:
        # Could also build on beta and nightly, but is it worth it?
        channel: [stable]
        os: [macos]
    steps:
    - uses: actions/checkout@v4
    - run: rustup default ${{ matrix.channel }}
    - name: Show toolchain versions
      run: |
        cargo --version --verbose
        rustc --version --verbose
    - name: Build application
      run: cargo build --verbose --all-targets
    - name: Show version information
      run: cargo run -- version
    - name: Run tests
      # network tests can be a bit flaky, so try up to two times
      run: cargo test || cargo test
