# This workflow checks that the application builds properly when using an older
# version of the Rust compiler.
name: Minimum Supported Rust Version

on: push

jobs:
  msrv:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - name: Install packages
      run: sudo apt-get install -y curl gcc g++ libsqlite3-dev wget libssl-dev pkg-config
    - name: Rustup MSRV
      run: |
        wget -O /tmp/ru.sh https://sh.rustup.rs
        chmod u+x /tmp/ru.sh
        /tmp/ru.sh -y --profile minimal --default-toolchain 1.63.0
        source $HOME/.cargo/env
        export PATH="$HOME/.cargo/bin:$PATH"
    - name: List installed Rust and Cargo version
      run: |
        rustc --version
        cargo --version
    - name: Show application version
      run: |
        cargo run -- version
    - name: Run tests
      # network tests can be a bit flaky, so try up to two times
      run: |
        cargo test || cargo test
