name: Rust application tests

on: [ push, pull_request ]

jobs:
  rust_tests:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Install packages
      run: |
        sudo apt-get update
        sudo apt-get install -y cargo rustc libssl-dev pkg-config
    - name: Build application
      run: |
        cargo build
    - name: Show version information
      run: |
        cargo run -- version
    - name: Run tests
      run: |
        cargo test
