# This workflow checks that the application builds properly when using an older
# version of the Rust compiler.
name: Minimum Supported Rust Version

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  clippy:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Install packages
      run: sudo apt-get install -y curl gcc g++ libsqlite3-dev wget
    - name: Rustup MSRV
      run: |
        wget -O /tmp/ru.sh https://sh.rustup.rs
        chmod u+x /tmp/ru.sh
        /tmp/ru.sh -y --profile minimal --default-toolchain 1.40
        source $HOME/.cargo/env
        export PATH="$HOME/.cargo/bin:$PATH"
    - name: List installed Rust and Cargo version
      run: |
        rustc --version
        cargo --version
    - name: Run tests
      run: |
        cargo test
